### ISSUE TITLE
Prep before the hackathon?

### ISSUE THREAD

**Issue by choldgraf** [Reproducible-Science-Curriculum/RR-Jupyter-Hackathon-Jan-2016#1]
Anything we should prep before the hackathon?

**Comment by hlapp** [comment]
Thanks @choldgraf for asking proactively! I just sent everyone the following principle tasks:

1. Those who haven't yet, accept the invitation to the repo team. This will by default also enable notifications about tracker activities in this repo.
2. Check (and if necessary correct) your information on the [Participants wiki page](https://github.com/Reproducible-Science-Curriculum/RR-Jupyter-Hackathon-Jan-2016/wiki/Participants). Then please add yourself to the [participant intros](https://github.com/Reproducible-Science-Curriculum/RR-Jupyter-Hackathon-Jan-2016/wiki/Participant-Intros).
 3. Post your ideas, lesson pitches, questions, and material suggested for consideration to [this issue tracker](https://github.com/Reproducible-Science-Curriculum/RR-Jupyter-Hackathon-Jan-2016/issues).
4. Please monitor the [agenda page](https://github.com/Reproducible-Science-Curriculum/RR-Jupyter-Hackathon-Jan-2016/wiki/Agenda) for late-breaking changes, and plan to be there for breakfast.

**Comment by choldgraf** [comment]
Sounds good - I'll leave this open in case other people come looking, but feel free to close if you like.

**Comment by choldgraf** [comment]
seems like there's a lot of healthy discussion now, so I'll close this
